Repository The-Art-of-Hacking/h4cker, pull requests merged in 2024-11, with the labels that each got.

#229 Update license reference
  README.md
Labels: broken link

#233 Update README.md with CyberPython
  vulnerable_servers/README.md
Labels: new resource

#236 organizing learning platforms
  vulnerable_servers/README.md
Labels: enhancement
